name       : python-ipykernel
version    : 4.6.1
release    : 1
source     :
    - https://github.com/ipython/ipykernel/archive/4.6.1.tar.gz : b52022f5a1bd026862ec49195f7ce2c915fbd9772c9e04ce4e778dba159d92a6
license    : BSD-3-Clause
component  : programming.python
summary    : IPython Kernel for Jupyter.
description: |
    IPython Kernel for Jupyter.
builddeps  :
    - pkgconfig(python-3.5)
    - python-ipython
    - python-jupyter_client
    - python-setuptools
    - python3-ipython
rundeps    :
    - python-ipython
    - python-jupyter_client
    - python-tornado
    - python-traitlets
    - python3-ipython
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
