name       : python-ipykernel
version    : 4.8.2
release    : 5
source     :
    - https://github.com/ipython/ipykernel/archive/4.8.2.tar.gz : 8d603e0561c303a47e6b6445ca5770a477f094451ec4af3d395e429e8439cdb3
license    : BSD-3-Clause
component  : programming.python
summary    : IPython Kernel for Jupyter.
description: |
    IPython Kernel for Jupyter.
builddeps  :
    - pkgconfig(python3)
    - python-ipython
    - python-jupyter_client
    - python-setuptools
    - python-traitlets
    - python3-ipython
rundeps    :
    - python-ipython
    - python-jupyter_client
    - python-tornado
    - python-traitlets
    - python3-ipython
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
    install -Dm00644 $pkgfiles/kernel.json $installdir/usr/share/jupyter/kernels/python3/kernel.json
