name       : python-ipykernel
version    : 6.13.0
release    : 15
source     :
    - https://files.pythonhosted.org/packages/source/i/ipykernel/ipykernel-6.13.0.tar.gz : 0e28273e290858393e86e152b104e5506a79c13d25b951ac6eca220051b4be60
homepage   : https://github.com/ipython/ipykernel
license    : BSD-3-Clause
component  : programming.python
summary    : IPython Kernel for Jupyter
description: |
    IPython Kernel for Jupyter.
builddeps  :
    - python-flaky          # check
    - python-ipyparallel    # check
    - python-jupyter_client
    - python-nest-asyncio   # check
    - python-nose           # check
    - python-pytest         # check
    - python-pytest-timeout # check
rundeps    :
    - python-debugpy
    - python-jupyter_client
    - python-nest-asyncio
    - python3-ipython
setup      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test pytest3 -v
