name       : python-ipykernel
version    : 6.9.2
release    : 13
source     :
    - https://files.pythonhosted.org/packages/source/i/ipykernel/ipykernel-6.9.2.tar.gz : 4c3cc8cb359f2ead70c30f5504971c0d285e2c1c699d2ce9af0216fe9c9fb17c
homepage   : https://github.com/ipython/ipykernel
license    : BSD-3-Clause
component  : programming.python
summary    : IPython Kernel for Jupyter
description: |
    IPython Kernel for Jupyter.
builddeps  :
    - python-flaky          # check
    - python-ipyparallel    # check
    - python-jupyter_client
    - python-nest-asyncio   # check
    - python-nose           # check
    - python-pytest         # check
rundeps    :
    - python-debugpy
    - python-jupyter_client
    - python-nest-asyncio
    - python3-ipython
setup      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test pytest3 -v
