name       : python-ipykernel
version    : 5.3.2
release    : 8
source     :
    - https://github.com/ipython/ipykernel/archive/5.3.2.tar.gz : e3c01ebe970ccfee6f415907be1641e2ce43fb2a1a7eebd14c8488bb85395d9f
license    : BSD-3-Clause
component  : programming.python
summary    : IPython Kernel for Jupyter
description: |
    IPython Kernel for Jupyter.
builddeps  :
    - pkgconfig(python3)
    - python3-ipython
    - python-flaky
    - python-jupyter_client
    - python-nose
    - python-pytest
rundeps    :
    - python3-ipython
    - python-jupyter_client
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v -k 'not test_is_complete'
