name       : python-ipykernel
version    : 6.15.2
release    : 17
source     :
    - https://files.pythonhosted.org/packages/source/i/ipykernel/ipykernel-6.15.2.tar.gz : e7481083b438609c9c8a22d6362e8e1bc6ec94ba0741b666941e634f2d61bdf3
homepage   : https://github.com/ipython/ipykernel
license    : BSD-3-Clause
component  : programming.python
summary    : IPython Kernel for Jupyter
description: |
    IPython Kernel for Jupyter.
builddeps  :
    - matplotlib            # check
    - python-build
    - python-debugpy        # check
    - python-hatchling
    - python-installer
    - python-flaky          # check
    - python-ipyparallel    # check
    - python-jupyter_client
    - python-nest-asyncio
    - python-pytest         # check
    - python-pytest-timeout # check
    - python-trio           # check
rundeps    :
    - python-debugpy
    - python-jupyter_client
    - python-nest-asyncio
    - python3-ipython
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
