name       : python-ipykernel
version    : 5.3.4
release    : 9
source     :
    - https://github.com/ipython/ipykernel/archive/5.3.4.tar.gz : f363a7331074f18d6fdbc49010ed2d06aac834fa23dbb6d7fd9f59d9b5e5056b
homepage   : https://github.com/ipython/ipykernel
license    : BSD-3-Clause
component  : programming.python
summary    : IPython Kernel for Jupyter
description: |
    IPython Kernel for Jupyter.
builddeps  :
    - pkgconfig(python3)
    - python-flaky
    - python-jupyter_client
    - python-nose
    - python-pytest
    - python3-ipython
rundeps    :
    - python-jupyter_client
    - python3-ipython
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v
