name       : python-ipykernel
version    : 4.7.0
release    : 2
source     :
    - https://github.com/ipython/ipykernel/archive/v4.7.0.tar.gz : 8807bd058a1b1b617cf9911632ad31f640200a1a59f3bd80fc799d8502a94a77
license    : BSD-3-Clause
component  : programming.python
summary    : IPython Kernel for Jupyter.
description: |
    IPython Kernel for Jupyter.
builddeps  :
    - pkgconfig(python-3.5)
    - python-ipython
    - python-jupyter_client
    - python-setuptools
    - python3-ipython
rundeps    :
    - python-ipython
    - python-jupyter_client
    - python-tornado
    - python-traitlets
    - python3-ipython
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
