name       : python-ipykernel
version    : 4.8.0
release    : 4
source     :
    - https://github.com/ipython/ipykernel/archive/4.8.0.tar.gz : 59adc3c9c23c959a767a293e68e308b4534037f73ca8980fa04e75ace3113023
license    : BSD-3-Clause
component  : programming.python
summary    : IPython Kernel for Jupyter.
description: |
    IPython Kernel for Jupyter.
builddeps  :
    - pkgconfig(python3)
    - python-ipython
    - python-jupyter_client
    - python-setuptools
    - python-traitlets
    - python3-ipython
rundeps    :
    - python-ipython
    - python-jupyter_client
    - python-tornado
    - python-traitlets
    - python3-ipython
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
