name       : python-ipykernel
version    : 6.7.0
release    : 11
source     :
    - https://github.com/ipython/ipykernel/archive/refs/tags/v6.7.0.tar.gz : cbe3531e10153194699c91563148b64204085204c6a87c7f5c80a5697d15caee
homepage   : https://github.com/ipython/ipykernel
license    : BSD-3-Clause
component  : programming.python
summary    : IPython Kernel for Jupyter
description: |
    IPython Kernel for Jupyter.
builddeps  :
    - python-flaky          # check
    - python-ipyparallel    # check
    - python-jupyter_client
    - python-nest-asyncio   # check
    - python-nose           # check
    - python-pytest         # check
rundeps    :
    - python-debugpy
    - python-jupyter_client
    - python-nest-asyncio
    - python3-ipython
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v
